---
sudo: false
language: ruby
cache: bundler
gemfile:
  - gemfiles/rspec_3.5.0.gemfile
  - gemfiles/rspec_3.6.0.gemfile
  - gemfiles/rspec_3.7.0.gemfile
rvm:
  - 2.5.0
  - 2.4.0
  - 2.3.0
  - truffleruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem update --system 2.6.14.1
  - gem install bundler -v 1.17.3
